# Generated by Django 4.1.2 on 2022-10-26 04:59

from django.db import migrations, models
import foot.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to=foot.models.user_directory_path)),
            ],
        ),
    ]
